"""Changed to use encrypted DB

Revision ID: 0ee6f1f73170
Revises: 1ea2f0ccfa23
Create Date: 2024-11-16 17:23:23.611482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee6f1f73170'
down_revision: Union[str, None] = '1ea2f0ccfa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_encrypted', sa.String(), nullable=False))
    op.add_column('users', sa.Column('image_encrypted', sa.String(), nullable=True))
    op.drop_column('users', 'image')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('users', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'image_encrypted')
    op.drop_column('users', 'name_encrypted')
    # ### end Alembic commands ###
